spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbo
    username: root
    password: Axis@123
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      pool-name: tej-test